//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/chenjinsong/RiderProjects/SchemeSharp/SchemeSharp/Sexpr.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrGen {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SexprParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ISexprListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SexprParser.sexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSexpr([NotNull] SexprParser.SexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SexprParser.sexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSexpr([NotNull] SexprParser.SexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SexprParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] SexprParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SexprParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] SexprParser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SexprParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] SexprParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SexprParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] SexprParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SexprParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] SexprParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SexprParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] SexprParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SexprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] SexprParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SexprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] SexprParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SexprParser.quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuote([NotNull] SexprParser.QuoteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SexprParser.quote"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuote([NotNull] SexprParser.QuoteContext context);
}
} // namespace AntlrGen
